logging.level: info

filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
            or:
              - contains:
                  docker.container.name: "orders-service"
              - contains:
                  docker.container.name: "payment-service"
          config:
            - type: container
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log
              processors:
                - add_docker_metadata: ~
                - decode_json_fields:
                    fields: ["message"]
                    process_array: false
                    max_depth: 1
                    target: ""
                    overwrite_keys: true
                - add_fields:
                    fields:
                      app: "${data.docker.container.labels.com.docker.compose.service}"
                    target: "fields"

output.logstash:
  hosts: ["logstash:5044"]
