{
 "title": "Observability Showcase",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service_name",
    "query": "\"orders-service\",\"payment-service\""
   }
  ]
 },
 "panels": [
  {
   "title": "500 - Error Rate %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum(\r\n    rate(http_server_duration_milliseconds_count{http_status_code=~\"5..\", exported_job=$service_name}[5m])\r\n  )\r\n  /\r\n  sum(\r\n    rate(http_server_duration_milliseconds_count{exported_job=$service_name}[5m])\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "clamp_max(time() - last_over_time(app_heartbeat{exported_job=$service_name}[30s]) < 15, 1) OR app_heartbeat{exported_job=$service_name} * 0 OR absent(app_heartbeat{exported_job=$service_name}) * 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query (p95)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,\r\n  sum(rate(http_server_duration_milliseconds_bucket{exported_job=$service_name}[5m])) by (le, http_method, http_route)\r\n)",
     "legendFormat": "{{http_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "400 - Error Rate %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum(\r\n    rate(http_server_duration_milliseconds_count{http_status_code=~\"4..\", exported_job=$service_name}[5m])\r\n  )\r\n  /\r\n  sum(\r\n    rate(http_server_duration_milliseconds_count{exported_job=$service_name}[5m])\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Series",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(v8js_memory_heap_used_bytes{exported_job=$service_name}) by (service_name) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query (p99)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\r\n  sum(rate(http_server_duration_milliseconds_bucket{exported_job=$service_name}[5m])) by (le, http_method, http_route)\r\n)",
     "legendFormat": "{{http_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{exported_job=$service_name}[1m])) \r\n  by (http_method, http_route)",
     "legendFormat": "{{http_method}} {{http_route}}"
    }
   ]
  }
 ]
}